# Generated by Django 4.2.7 on 2023-11-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
